removing explicit calls to subscribers request method.
FortnoxAB/reactive-wizard pull request #211
Opened 2020-09-24 13:49 UTC by rassmate

Removing unwanted calls to subscribers request method.

All tests still passes so I take that as a good sign and will not add new tests just for this

2020-09-24 14:03 UTC, JonasHallFnx approved these changes

2020-09-24 19:38 UTC, magnusp requested changes

2020-09-24 19:38 UTC, magnusp commented on metrics/src/main/java/se/fortnox/reactivewizard/metrics/MetricsOperator.java
> -                this.subscription.request(Long.MAX_VALUE);
Weird results over at sonarcloud but I don't think we have any tests at all covering MetricsOperator. Perhaps we should test this with an application that uses it?

2020-09-25 07:44 UTC, magnusp commented on metrics/src/main/java/se/fortnox/reactivewizard/metrics/MetricsOperator.java
> -                this.subscription.request(Long.MAX_VALUE);
Tested with internal application and both timers and counters were published on incoming requests

2020-09-25 07:44 UTC, magnusp approved these changes

2020-09-25 07:56 UTC, merged