Added possibility to suppress missing path param errors.
FortnoxAB/reactive-wizard pull request #246
Opened 2021-06-11 11:35 UTC by j-holmstrom

There were issues with some client interfaces having path params that was later resolved by RW internal so we need some way to get around those kind of use cases.

2021-06-11 12:51 UTC, flowertwig requested changes

2021-06-11 12:51 UTC, flowertwig commented on jaxrs-api/src/main/java/se/fortnox/reactivewizard/jaxrs/SuppressMissingPathParam.java
> +    String[] paramName() default "";
Should we mention that it's case sensitive?

2021-06-11 12:51 UTC, flowertwig commented on jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/CheckForMissingPathParams.java
> +                            "If this is intended, the error can be suppressed with @SupressMissingPathParam.",
@SuppressMissingPathParam

2021-06-14 07:24 UTC, flowertwig approved these changes

2021-06-14 07:43 UTC, rassmate commented on jaxrs/src/test/java/se/fortnox/reactivewizard/jaxrs/MissingPathParamTestInteraces.java
> +public class MissingPathParamTestInteraces {
nit: Interfaces

2021-06-14 07:50 UTC, rassmate approved these changes

2021-06-14 08:08 UTC, merged