Feature/log4j2 from config files
FortnoxAB/reactive-wizard pull request #269
Opened 2021-12-23 13:23 UTC by j-holmstrom

Migrated to log4j2. We adapted log42j configuration instead of having it in the config.yml with loggingfactory. The reason for this was that we want to do the logging configuration more flexible without requiring changes to the framework. As well we could remove a lot of code that just converted between our format and the format log4j.

2021-12-27 06:27 UTC, jepp3 approved these changes

2021-12-28 07:07 UTC, rassmate approved these changes

2022-01-03 15:04 UTC, JonasHallFnx approved these changes

2022-01-04 06:25 UTC, rassmate requested changes
Removing the logging module also removes the central place for specifying which version of slf4j we are using.

So wherever we remove the logging-dependency, we should add a dependency to slf4j-api module so the code does not get the dependency from some shady lib we didnt expect.

Perhaps add it to the dependencyManagement section of the root-pom to avoid version conflicts.

2022-01-10 12:51 UTC, rassmate approved these changes

2022-01-10 12:51 UTC, merged