Support for JUnit 5
FortnoxAB/reactive-wizard pull request #375
Opened 2022-08-17 10:29 UTC by softqwewasd

2022-08-17 10:47 UTC, flowertwig reviewed
I think we should migrate one or two test classes to junit5 just to show that it works.

2022-08-17 10:47 UTC, flowertwig commented on test/pom.xml
> +        <dependency>
We should remove this if not needed.

2022-08-17 13:37 UTC, rassmate approved these changes
GJ!

2022-08-19 07:49 UTC, jepp3 commented on test/src/test/java/se/fortnox/reactivewizard/examples/junit5_examples/Junit5Tests.java
> +class Junit5Tests {
I think we should remove these pure example test cases. We can state in the reactive wizard documentation in backstage that junit5 is supported out of the box maybe.

2022-08-19 07:50 UTC, jepp3 requested changes
I think we should remove these pure example test cases. We can state in the reactive wizard documentation in backstage that junit5 is supported out of the box maybe.

2022-08-19 13:56 UTC, softqwewasd commented
The example code has been removed. I migrated a test class in the _jaxrs_ module from JUnit 4 to JUnit 5 since I could not find tests in the _test_ module that are fit to be migrated into an example parameterized test.

2022-08-22 06:55 UTC, jepp3 approved these changes

2022-08-22 11:58 UTC, flowertwig approved these changes

2022-08-25 08:10 UTC, rassmate commented on test/src/test/java/se/fortnox/reactivewizard/test/LoggingInfoVerifierTest.java
> +import org.junit.jupiter.params.ParameterizedTest;
unused import?

2022-08-25 08:11 UTC, rassmate approved these changes

2022-08-29 07:16 UTC, merged