Returning 400 when the deserialized body in a HTTP request is null
FortnoxAB/reactive-wizard pull request #382
Opened 2022-08-29 06:48 UTC by softqwewasd

2022-08-29 07:13 UTC, rassmate commented on jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/params/ParamResolverFactories.java
> +                return Mono.just(deserializeBody(bodyDeserializer, request.getBody()));
You could just send in deserializedBody in instead of deserializing it once again.

2022-08-29 07:21 UTC, flowertwig requested changes

2022-08-29 07:21 UTC, flowertwig commented on jaxrs/src/main/java/se/fortnox/reactivewizard/jaxrs/params/ParamResolverFactories.java
> +                    return Mono.error(new WebException(HttpResponseStatus.BAD_REQUEST, "body.deserializer.error", "Deserialized body is null"));
Just return bad request. Then warn log and include the body in the log.

2022-08-29 10:35 UTC, flowertwig approved these changes

2022-08-30 06:33 UTC, rassmate approved these changes

2022-08-30 06:44 UTC, merged